version: "3.7"

services:

  mongo:
    image: mongo:4.2.6
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=simple_object_storage
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - type: volume
        source: data
        target: /data/db
    ports:
      - "27017:27017"
    healthcheck:
      start_period: 30s
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/simple_object_storage --quiet
      interval: 15s
      timeout: 3s
      retries: 5

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    entrypoint: /usr/local/bin/mongo-express-entrypoint.sh
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    volumes:
      - ./mongo-express-entrypoint.sh:/usr/local/bin/mongo-express-entrypoint.sh
    ports:
      - "8081:8081"

volumes:
  data:
    driver: local
